server:
  port: ${PORT:8089}

spring:
  main:
    banner-mode: "off"
  application:
    name: issues-ms
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:root@localhost:27017/sv_issues?retryWrites=false&w=majority&sslInvalidHostNameAllowed=true&ssl=false}
      auto-index-creation: true
  cache:
    type: "redis"
  redis:
    host: "localhost"
    port: "6379"
    password: "redispw"

feignClient:
  votescount:
    uri: "http://localhost:8085"

springfox:
  documentation:
    swaggerUi:
      baseUrl: /documentation
    openApi:
      v3:
        path: /documentation/api-docs
    swagger:
      v2:
        path: /documentation/api-docs
