server:
  port: ${PORT:8085}

spring:
  main:
    banner-mode: "off"
  application:
    name: ${DEFAULT_APPLICATION_NAME:@project.name@}
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:root@localhost:27017/sv_votes?retryWrites=false&w=majority&sslInvalidHostNameAllowed=true&ssl=false}
      auto-index-creation: true

springdoc:
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui}
    enable: ${SPRINGDOC_SWAGGER_UI_ENABLE:true}
    disable-swagger-default-url: true
  api-docs:
    path: ${SPRINGDOC_APIDOCS_PATH:/api-docs}
    enable: ${SPRINGDOC_APIDOCS_ENABLE:true}

swagger-config:
  version: 1.0.0
  title: Authorization service - Educacional Positivo
  description: APIs responsible for managing roles and permission of the platform
  servers:
    develop:
      url: https://dev-lb.educacional.com/${DEFAULT_APPLICATION_NAME:@project.name@}
      description: Develop
    qa:
      url: https://qa-lb.educacional.com/${DEFAULT_APPLICATION_NAME:@project.name@}
      description: QA
    staging:
      url: https://stg-lb.educacional.com/${DEFAULT_APPLICATION_NAME:@project.name@}
      description: Homologation / Staging
    production:
      url: https://prd-lb.educacional.com/${DEFAULT_APPLICATION_NAME:@project.name@}
      description: Production
  responses:
    error:
      400: Problem with the data in the request
      403: Request violetes some authorization rule
      404: Resource requested not found
      422: Request violetes some business rule
      500: Some unexpected error has ocorred
      502: Service is unavaible at the moment